# Generated by Django 4.1.2 on 2022-11-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='Category',
        ),
        migrations.AddField(
            model_name='article',
            name='file_field',
            field=models.FileField(null=True, upload_to='file', verbose_name='محل ارسال فایل'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='articles', to='blogs.category', verbose_name='دسته بندی'),
        ),
    ]
