# Generated by Django 4.1.2 on 2022-11-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_article_options_remove_article_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='عنوان کتگوری')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='file_field',
        ),
    ]
