# Generated by Django 4.1.2 on 2022-11-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ve_thumbnail',
            field=models.ImageField(null=True, upload_to='images', verbose_name='جلوه مقاله '),
        ),
    ]
