# Generated by Django 4.1.2 on 2022-12-06 13:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description_img',
            field=models.TextField(default=True, verbose_name='متن زیر عکس'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='متن مقاله'),
        ),
    ]
