# Generated by Django 4.1.2 on 2022-12-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_article_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
