# Generated by Django 4.1.2 on 2023-01-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_delete_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(null=True, related_name='articles', to='blogs.category', verbose_name='دسته بندی'),
        ),
    ]
