# Generated by Django 4.1.2 on 2023-01-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='best_status',
            field=models.CharField(choices=[('n', 'نیست'), ('y', 'هست')], max_length=1, null=True, verbose_name='انیمه برتر ماه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='articles', to='blogs.category', verbose_name='دسته بندی'),
        ),
    ]
