# Generated by Django 4.1.2 on 2023-01-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_article_best_status_alter_article_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pub',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
