# Generated by Django 4.1.2 on 2023-01-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_delete_pub_remove_article_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='display_video',
            field=models.FileField(default=True, upload_to='video/%y'),
        ),
    ]
