# Generated by Django 4.1.2 on 2023-01-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_article_video_title_alter_article_display_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='display_video',
        ),
        migrations.RemoveField(
            model_name='article',
            name='video_title',
        ),
    ]
