# Generated by Django 4.1.2 on 2023-01-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0020_ipaddress_article_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user_address',
        ),
        migrations.AddField(
            model_name='article',
            name='user_ip_address',
            field=models.ManyToManyField(blank=True, related_name='user_ip_address', to='blogs.ipaddress', verbose_name='user_ip'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='user_ip',
            field=models.GenericIPAddressField(verbose_name='user_ip'),
        ),
    ]
