# Generated by Django 4.1.2 on 2023-01-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_remove_article_user_address_article_user_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description_img',
            field=models.TextField(verbose_name='متن زیر عکس'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user_ip_address',
            field=models.ManyToManyField(blank=True, related_name='user_ip_address', to='blogs.ipaddress', verbose_name='بازدید ها'),
        ),
    ]
